<project name="MPFS_DISCOVERY_KIT" version="1.2">
    <ProjectDirectory>
        C:\Users\Danug\Documents\Code\SecureVISION-polarfire-reference-design\MPFS_DISCOVERY\designer\MPFS_DISCOVERY_KIT\MPFS_DISCOVERY_KIT_fp
    </ProjectDirectory>
    <View>
        ChainView
    </View>
    <LiberoTargetDevice>
        MPFS095T
    </LiberoTargetDevice>
    <LogFile>
        C:\Users\Danug\Documents\Code\SecureVISION-polarfire-reference-design\MPFS_DISCOVERY\designer\MPFS_DISCOVERY_KIT\MPFS_DISCOVERY_KIT_fp\MPFS_DISCOVERY_KIT.log
    </LogFile>
    <SerializationOption>
        Skip
    </SerializationOption>
    <ProgrammingInterface>
        JTAGMode
    </ProgrammingInterface>
    <programmer status="enable" type="FlashPro5" revision="UndefRev" connection="usb1.1">
        <name>
            E2009OS1XR
        </name>
        <id>
            E2009OS1XR
        </id>
    </programmer>
    <Servers>
    </Servers>
    <configuration>
        <Hardware>
            <FlashPro>
                <TCK>
                    4000000
                </TCK>
                <Vpp/>
                <Vpn/>
                <Vddl/>
                <Vdd>
2500                </Vdd>
            </FlashPro>
            <FlashProLite>
                <TCK>
                    4000000
                </TCK>
                <Vpp/>
                <Vpn/>
            </FlashProLite>
            <FlashPro3>
                <TCK>
                    4000000
                </TCK>
                <ClkMode>
                    FreeRunningClk
                </ClkMode>
            </FlashPro3>
            <FlashPro4>
                <TCK>
                    4000000
                </TCK>
                <ClkMode>
                    FreeRunningClk
                </ClkMode>
            </FlashPro4>
            <FlashPro5>
                <TCK>
                    4000000
                </TCK>
                <ClkMode>
                    DiscreteClk
                </ClkMode>
            </FlashPro5>
            <FlashPro6>
                <TCK>
                    4000000
                </TCK>
                <SCK>
                    20000000
                </SCK>
                <ClkMode>
                    DiscreteClk
                </ClkMode>
            </FlashPro6>
        </Hardware>
        <Device type="ACTEL">
            <Name>
                MPFS095T
            </Name>
            <Custom>
                MPFS095T
            </Custom>
            <SpiFlashFile>
                
            </SpiFlashFile>
            <SpiFlashSelectedAction>
                
            </SpiFlashSelectedAction>
            <Algo type="unknown">
                <irlength>
                    8
                </irlength>
                <MaxTCK>
                    25000000
                </MaxTCK>
            </Algo>
        </Device>
        <Algo type="unknown">
            <irlength>
                0
            </irlength>
            <MaxTCK>
                0
            </MaxTCK>
        </Algo>
    </configuration>
</project>
